import { backgroundImg } from '@/styles/background.css';
import Image from 'next/image';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <Image
          src="/assets/background.png"
          alt="background"
          fill={true}
          className={backgroundImg}
        />
        {children}
      </body>
    </html>
  );
}
